### ISSUE TITLE
This project needs a maintainer.

### ISSUE THREAD

**Issue by bashu** [fusionbox/django-absoluteuri#11]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you!

**Comment by bashu** [comment]
cc @gavinwahl @selectnull @acatton

**Comment by bashu** [comment]
If you are not sure about me, for example I maintain (or helping):

https://github.com/shanx/django-maintenancemode

https://github.com/adamcharnock/django-tz-detect

Also I adopted few Django projects and still continue maintaining them, biggest example:

https://github.com/bashu/django-easy-maps

**Comment by bashu** [comment]
anyone?

**Comment by bashu** [comment]
to @nolsto can you look into this one?

**Comment by hugoseabra** [comment]
Completely forgotten.

@bashu , did your find some reasonable alternative to this package?

**Comment by bashu** [comment]
to @hugoseabra alas no

**Comment by selectnull** [comment]
@bashu Since you've tagged me and I never replied, maybe I could just quickly give my oppinion on this issue.
I have no relation to this project other than a submission I made and I can't decide one way or the other on its future. You clearly want to take maintenance of this project but the current owner is not replying and at this stage I don't think is reasonable to assume they ever will (they don't owe anything to anybody).

So, if you really are that interested in this package, why don't you fork it, republish it under another name and give the new package all the love and maintenance it needs?

**Comment by bashu** [comment]
to @selectnull I will...
